[package]
name = "dprint-plugin-taplo"
version = "0.1.1"
authors = ["Tice Cosmos <tice@139.com>"]
edition = "2018"


[lib]
crate-type = ["lib", "cdylib"]


[features]
wasm = ["serde_json", "dprint-core/wasm"]


[dependencies]
dprint-core = { version = "0.35", features = ["formatting"] }
taplo = { version = "0.5", features = ["schema", "serde", "verify"] }

serde = { version = "*", features = ["derive"] }

serde_json = { version = "*", optional = true }
