[package]
name = "dprint-plugin-taplo"
version = "0.1.0"
authors = ["Tice Cosmos <tice@139.com>"]
edition = "2018"


[lib]
crate-type = ["lib", "cdylib"]


[features]
wasm = ["serde_json", "dprint-core/wasm", "taplo/schema", "taplo/serde", "taplo/verify"]


[dependencies]
dprint-core = { version = "0.35", features = ["formatting"] }
taplo = "0.5"

serde = { version = "*", features = ["derive"] }

serde_json = { version = "*", optional = true }
